### ISSUE TITLE
Vue initialized twice

### ISSUE THREAD

**Issue by trapcodeio** [NightCatSama/vue-slider-component#342]
[<img alt="Issuehunt badges" src="https://issuehunt.io/r/NightCatSama/vue-slider-component/issues/342/badge.svg" />](https://issuehunt.io/r/NightCatSama/vue-slider-component/issues/342)

#### Describe the bug
After including slider for use
```javascript
 import  VueSlider from 'vue-slider-component'; 
 Vue.component('VueSlider', VueSlider);
```
I see the vue development message twice.

```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

The first from my main `needed.js` where i initialized my vue.
The second is from `webapp.js` where i included the slider.

When i click on any element after adding this slider i get this error.
```
[Vue warn]: $attrs is readonly.
```

From this [post on stackoverflow](https://stackoverflow.com/questions/49585845/attrs-is-readonly-listeners-is-readonly-avoid-mutating-a-prop-directly):
_The $attrs, $listeners and other warnings are displayed if there's more than one instance of Vue loaded_

Is there anything i can do to resolve this?

Vue: **2.6.10**
Vue-router: **3.0.3**
Vue-slider-component: **3.0.36**

> There is a $50.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/NightCatSama/vue-slider-component/issues/342).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/NightCatSama/vue-slider-component/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

**Comment by NightCatSama** [comment]
Are you using the `3.0.26` version? 

The 3.0.26 version should not contain the `vue` dependency.

**Comment by nilsE** [comment]
same here, also with 3.0.26

**Comment by NightCatSama** [comment]
Is it a problem with the component? Does this error occur without using the component?

**Comment by nilsE** [comment]
i'm using https://github.com/RobertBoes/nova-slider-field for laravel/nova, it uses your component.
branch 2.x works fine, but with 3.x the slider is not showing up at all and vue is loaded twice
without the component everything's fine.

<img width="500" alt="screenshot_709" src="https://user-images.githubusercontent.com/1436929/55866687-24ee0c00-5b81-11e9-9d6a-8a4dc0b976de.png">

**Comment by NightCatSama** [comment]
This library uses components of the v2.x version.

https://github.com/RobertBoes/nova-slider-field/blob/29a959b56f75c376ca55c97cef77818a9bb4548e/package.json#L19

I don't know if it matters, I have not used Laravel Nova 😞 .

**Comment by nilsE** [comment]
sure, updated that to 3.0.26

**Comment by NightCatSama** [comment]
Sorry, I have no other ideas 😭 .

**Comment by trapcodeio** [comment]
@NightCatSama yes am using version 3.0.26 

It works fine in production but throws error in development

I still can't find a solution too

**Comment by trapcodeio** [comment]
Any help with this yet?

**Comment by NightCatSama** [comment]
@trapcodeio I can't reproduce this question, can you provide more information, such as the build environment (`webpack.config.js` or `vue.config.js`) and how you introduced vue and components.

**Comment by trapcodeio** [comment]
> @trapcodeio I can't reproduce this question, can you provide more information, such as the build environment (`webpack.config.js` or `vue.config.js`) and how you introduced vue and components.

I explained how i introduced the component in the main post.
The error shows on **development** but not in production.

see the error in the image below.
**needed.js** is where i initialized my vue.
**webapp.js** is where vue-silder-component is included.

this happens once i require or import, even before setting vue to use it.
The second development message in webapp.js shows once i import or require vue-silder-component

i use laravel-mix with laravel so i don't have any of the files you mentioned above.

![Screenshot from 2019-04-12 19-14-57](https://user-images.githubusercontent.com/48396844/56057670-4e609080-5d57-11e9-86e2-423ff64a7cd4.png)

**Comment by NightCatSama** [comment]
@trapcodeio Wouldn't an error occur if `v-model` is not used on the component?

**Comment by trapcodeio** [comment]
> @trapcodeio Wouldn't an error occur if `v-model` is not used on the component?

The error occurs on import or require, even without adding `vue-slider` in template.

For now i only add the slider when i want to build for production then comment them out in development.

**Comment by NightCatSama** [comment]
@trapcodeio Try executing `npm ls vue` in your project to see if there are two vue.

If so, try deleting and reinstall dependencies.

**Comment by shuhankuang** [comment]
I got the same error.
vue@2.6.10
vue-slider-component@3.0.27
buefy@0.7.4

<img width="328" alt="QQ20190416-204318@2x" src="https://user-images.githubusercontent.com/251948/56210406-5c305180-6088-11e9-834b-809ff00237bc.png">

**Comment by NightCatSama** [comment]
I used the project created by the [Laravel document](https://laravel.com/docs/5.8) and did not report an error 😢 .

<details>
  <summary>related code</summary>

#### Create-Project
```
composer create-project --prefer-dist laravel/laravel blog
```

#### ./resources/js/components/ExampleComponent.vue
```vue
<template>
    <div class="container">
        <vue-slider :width="400" />
    </div>
</template>

<script>
    import VueSlider from 'vue-slider-component'
    export default {
        components: {
            VueSlider,
        },
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

<style>
    .container {
        padding: 30px;
    }
</style>
```
</details>

Before this problem can be solved, can try using [v2.x](https://github.com/NightCatSama/vue-slider-component/tree/v2).

I hope someone can solve this problem or provide a reproducible program.

**Comment by Stereotip42** [comment]
And I got the same error after update :(

![image](https://user-images.githubusercontent.com/9520187/56592002-77eca800-65f2-11e9-84e2-9becd135f7ea.png)
![image](https://user-images.githubusercontent.com/9520187/56592030-876bf100-65f2-11e9-99f9-1c41bad3a66b.png)

**Comment by NightCatSama** [comment]
@Stereotip42 What is your development environment?

**Comment by Stereotip42** [comment]
@NightCatSama its development environment

**Comment by NightCatSama** [comment]
@Stereotip42  What is the Laravel version?

**Comment by Stereotip42** [comment]
@NightCatSama 5.8 version, that's just recently updated from 5.7

**Comment by NightCatSama** [comment]
@Stereotip42 Try using `vue-slider-component/dist/vue-slider-component.common.js`

**Comment by Erutan409** [comment]
@NightCatSama As far as I can tell (using webpack), it looks like the way you're extending `Vue` is more than likely the culprit.  When I look at my script build, it's importing the entire Vue core functionality.  Since I was already pulling in Vue from a CDN (much more preferable), I'm deducing that's why I'm seeing it twice; possibly the same for others.

**Comment by IssuehuntBot** [comment]
@issuehunt has funded $50.00 to this issue.

---
- Submit pull request via [IssueHunt](https://issuehunt.io/repos/69530328/issues/342) to receive this reward.
- Want to contribute? Chip in to this issue via [IssueHunt](https://issuehunt.io/repos/69530328/issues/342).
- Checkout the [IssueHunt Issue Explorer](https://issuehunt.io/issues) to see more funded issues.
- Need help from developers? [Add your repository](https://issuehunt.io/r/new) on IssueHunt to raise funds.

**Comment by getninjaN** [comment]
First of all, thank you for an awesome component!
I love it.

Secondly,
I have the same problem in development no matter if I use `vue-slider-component.common` or `vue-slider-component.umd`.

vue version is **2.6.10**
vue-slider-component version is **3.0.36**

![image](https://user-images.githubusercontent.com/1355935/57316540-57dedd80-70f6-11e9-96e9-e44bc4d81b75.png)

From what I can find `vue.runtime.esm.js` is loaded from this line in `vue-slider-component.umd.min.js`.

```javascript
module.exports = e(__webpack_require__(/*! vue */ "./node_modules/vue/dist/vue.runtime.esm.js"))
```

I have tried a bunch of stuff but without success.

There are no errors in production however and the component still functions as it should in development, so it's not broken.
It's just annoying with the console getting wrecked by errors. :)

Not sure if this helps at all, I'm just tired from debugging and thought I'd share.

**Comment by NightCatSama** [comment]
@getninjaN Thank you for sharing.

This error should be caused by two copies of vue in app, but I don't know why this happened.

Can you provide me with a project that can restore the error, just need empty project.

**Comment by thiagorb** [comment]
I was having this same issue but it was due to how my bundle was being setup. In my case I need to have templates declared in .js files, so they must be compiled, and therefore the compiler must be included in the bundle.

In order to avoid importing `vue/dist/vue` in my components, I'm using `aliasify` to alias `vue` to either `vue/dist/vue` or `vue/dist/vue.min` (depending on whether I'm building for dev or production).

This was leading to vue being included twice in the bundle, once in `node_modules/vue/dist/vue.js` and once in `node_modules/vue/dist/vue.runtime.common.js`.

I was able to fix it by adding the flag `global: true` to the aliasify transform, so that the alias would also apply to vue-slider-component.

**Comment by mareczek** [comment]
@NightCatSama isn't something like this:
```javascript
  configureWebpack: {
    externals: {
      vue: 'vue'
    }
  },
```
missing from `vue.config.js`?

**Comment by NightCatSama** [comment]
@mareczek It seems that most of the errors are in the laravel environment, so there is no such `vue.config.js`.

**Comment by cvharris** [comment]
@mareczek was correct. Similarly in `webpack.config.js` all you have to do is:

```js
{
  ...
  externals: {
    vue: 'Vue'
  },
  ...
}
```

**Comment by arneysebaert** [comment]
Same problem here:

vue-slider-component: 3.0.33 (tried 3.0.26 and 2.x as well)
vue: 2.5.22

I also have 2 instances of Vue being loaded.

**Comment by davidlbean** [comment]
Specific to a Rails app:

Hmmm...I think I just got rid of my duplicate loading error...  Added this to my config/webpack/environment.js file:
```
// see https://stackoverflow.com/questions/53582944/how-to-properly-install-vuetify-for-rails
const resolver = {
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    }
  }
}
environment.config.merge(resolver)
```
Need to do some more testing to verify, but I thought I'd add this now for anyone using Rails and having the problem.

**Comment by getninjaN** [comment]
Thank you @davidlbean!
This solved the issue for me.

**Comment by michagee** [comment]
@davidlbean Not in Rails context, but same worked for me, thank you!

**Comment by IssueHuntBot** [comment]
@nightcatsama has rewarded $35.00 to @nightcatsama. [See it on IssueHunt](https://issuehunt.io/repos/69530328/issues/342)

- :moneybag: Total deposit: $50.00
- :tada: Repository reward(20%): $10.00
- :wrench: Service fee(10%): $5.00

**Comment by Jakob-Maudience** [comment]
My project is an electron environment, and I'm using [electron-webpack](https://github.com/electron-userland/electron-webpack) for bundling. 

The above "resolve" webpack config didn't work, but I was able to resolve by [whitelisting](https://webpack.electron.build/configuration.html#white-listing-externals) both the `vue` and `vue-slider-component` modules in my `elecronWebpack` settings in package.json

> Since webpack is set to target the electron environment, all modules are treated as externals. Unfortunately, there can be a few situations where this behavior may not be expected by some modules. For the case of some Vue UI libraries that provide raw *.vue components, they will needed to be white-listed. This ensures that vue-loader is able to compile them as the UI library originally expected.

package.json

```json
{
  ...
  "electronWebpack": {
    "whiteListedModules": [
      "vue",
      "vue-slider-component"
    ]
  }
}
```

Vue version: 2.6.10
vue-slider-component: 3.0.38
electron: 5.0.2
electron-webpack: 2.6.2

Hope this helps someone!

**Comment by CoffeeKing68** [comment]
Hi
I'm very new to webpack and compilation. If you wouldn't mind translating the solution for a laravel nova project (using laravel mix to compile).

Thanks

**Comment by fedeth** [comment]
> Specific to a Rails app:
> 
> Hmmm...I think I just got rid of my duplicate loading error... Added this to my config/webpack/environment.js file:
> 
> ```
> // see https://stackoverflow.com/questions/53582944/how-to-properly-install-vuetify-for-rails
> const resolver = {
>   resolve: {
>     alias: {
>       'vue$': 'vue/dist/vue.esm.js'
>     }
>   }
> }
> environment.config.merge(resolver)
> ```
> 
> Need to do some more testing to verify, but I thought I'd add this now for anyone using Rails and having the problem.

this works for me, but i dunno why

**Comment by olemarius** [comment]
I got the error in a plain vue app (no vuetify, laravel or anything) when vue.js was added to `<head>`. Once I removed that and added `import Vue from 'vue'` in main.js it worked. Vue version 2.6.11 and vue-slider-component 3.1.5.

I'm thinking if you add import vue in the component, my app is resolving that in the build process so it ends up importing only once, while in my case I added vue outside the app file main.js so it couldn't possibly know there's another vue. Makes sense? 

So if you set up a simple test like this and add vue-slider-component in app.js you should be able to reproduce the issue. 

```<html>
    <head>
        <title>Demo</title>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    </head>
    <body>
        <div class="container">
            <div id="app"></div>
        </div>
            <script src="app.js"></script>
    </body>
</html>```

**Comment by diegocharles** [comment]
> Specific to a Rails app:
> 
> Hmmm...I think I just got rid of my duplicate loading error... Added this to my config/webpack/environment.js file:
> 
> ```
> // see https://stackoverflow.com/questions/53582944/how-to-properly-install-vuetify-for-rails
> const resolver = {
>   resolve: {
>     alias: {
>       'vue$': 'vue/dist/vue.esm.js'
>     }
>   }
> }
> environment.config.merge(resolver)
> ```
> 
> Need to do some more testing to verify, but I thought I'd add this now for anyone using Rails and having the problem.

I own you a coffee buddy. 
I was having the same error here with my Rails app.

**Comment by borismacias** [comment]
> Specific to a Rails app:
> 
> Hmmm...I think I just got rid of my duplicate loading error... Added this to my config/webpack/environment.js file:
> 
> ```
> // see https://stackoverflow.com/questions/53582944/how-to-properly-install-vuetify-for-rails
> const resolver = {
>   resolve: {
>     alias: {
>       'vue$': 'vue/dist/vue.esm.js'
>     }
>   }
> }
> environment.config.merge(resolver)
> ```
> 
> Need to do some more testing to verify, but I thought I'd add this now for anyone using Rails and having the problem.

Its still working with version `3.2.3`, send me a link to buy you a beer 🍺

**Comment by james090500** [comment]
Using laravel mix, when using the command
```
npm install vue-slider-component --save 
```

it installs the component as a ``devDependencies`` and installs it to the local user node_modules (/home/james/node_modules) rather than the project directory. If I just use

```
npm install vue-slider-component
```

It installs it as a ``dependencies`` and into the project node_modules. (/home/james/project/node_nodues)

If the project is installed a ``dependencies`` rather than a ``devDependencies`` it seems to run fine. If it's installed as a ``devDependencies`` you get compilation errors. and "VueJS not found

**Comment by feldsam** [comment]
Hello, I am using Laravel Nova and developing my own Nova Tool. I think that this problem is caused by this component's explicit dependency on the Vue in conjunction with how Nova manages third-party code; there is `require('vue')` in dist JS.

Laravel Nova is shipped as the package with Vuejs installed, Nova extensions (tools, fields) have structure as composer package with own package.json and npm too. Problem is, that if I want to use this slider component, I have to install Vuejs in my Tool even it is installed in Laravel Nova. I can't compile Tool's resources without it.

The solution should be removing the explicit dependency on Vue from this package, so we can compile assets without installing second Vuejs in the Nova Tool/Field.

**Comment by trapcodeio** [comment]
I closed this because there seem to be a fixed above

**Comment by feldsam** [comment]
Hello, it still not fixed. It is possible to remove dep on vue?

**Comment by NightCatSama** [comment]
@feldsam It has been tested that the slider does not work in versions prior to vue2.6.0 after removing `require('vue')`.

So I updated it by releasing a beta version:
```bash
  yarn add vue-slider-component@beta
  # npm install vue-slider-component@beta --save
```

**Comment by feldsam** [comment]
Hello, perfect! Working now without ugly errors. Thank you!

**Comment by therealtimhawkins** [comment]
I had this problem when upgrading from `vue-cli` to `vite` and solved it by adding the alias in `vite.config.json`:
```
resolve: {
    alias: {
      vue: 'vue/dist/vue.esm.js'
    }
}
```
